### ISSUE TITLE
Understanding '_rooms_paths2020' variable and minor correction

### ISSUE THREAD

**Issue by sakshamsingh1** [danielkrause/DCASE2022-data-generator#3]
I am trying to recreate the synthetic data for DCASE SELD 2022 dataset. I wanted to understand `_rooms_paths2020` variable in here
https://github.com/danielkrause/DCASE2022-data-generator/blob/36c942ef8d7f6e8b30fd1861a93c0083188bb201/audio_mixer.py#L17-L20

I cannot find data for room `07_se201_sahkotalo_classroom` in the RIR dataset or Noise dataset. Also, when I tried to remove it I got `index out of bound` error. Is there a significance of this room variable or it's a mistake?

Also, in order to run the `example_script_DCASE2022.py` script, I had to change `refs_{}_{}` to `rirs_{}_{}` here https://github.com/danielkrause/DCASE2022-data-generator/blob/36c942ef8d7f6e8b30fd1861a93c0083188bb201/audio_synthesizer.py#L53-L56

**Comment by sreenivasaupadhyaya** [comment]
@sakshamsingh1   Did you use this code successfully for your application?

**Comment by sakshamsingh1** [comment]
Hi, yes I was able to use this code. 
Apart from the changes above, I had to do some additional tweaks to run it.

**Comment by sreenivasaupadhyaya** [comment]
> Hi, yes I was able to use this code. Apart from the changes above, I had to do some additional tweaks to run it.

Thanks for your reply. 

1. Could you please share ur code if possible and also the python and package version which you used.
2.  Also, did you face anything as i mentioned in this issue: https://github.com/danielkrause/DCASE2022-data-generator/issues/5

**Comment by sakshamsingh1** [comment]
1. Sure, give me some time. I will have to revisit and clean the scripts. 
2. I don't remember. But you have to update the example_script to run it on your system, like changing the location path of data mentioned in the example script.

**Comment by sreenivasaupadhyaya** [comment]
I did make changes as you mentioned in step 2. The script does run and generate output files (wav file with mixed events _ RIR + noise). However, the script fails everytime somewhere in betweeen due to errors like i mentioned in the #5 issue.
So I am bit curious if I am doing something wrong or my environment (Python + packages) has some issues?

Looking forwad to your code (its fine if its not clean and could work by just changing the paths) or atleast to compare and see the major differences in the code.

Thanks in advance.

**Comment by danielkrause** [comment]
Hey Saksham,

Thanks for the comments and sorry for the reply (although we talked already and I guess you arleady figured all the problems out). I changed the things you mentioned - indeed the RIRs are under the "rirs(...)" filenames now, so that had to be changed.
However, the seventh room needs to stay in the room list, since it's also present in the rirdata datafile.

**Comment by sakshamsingh1** [comment]
Hey @sreenivasaupadhyaya , here is the code : https://github.com/sakshamsingh1/synth_data_generator
