### ISSUE TITLE
A little comment on the training environment

### ISSUE THREAD

**Issue by ycyang133** [danielkrause/DCASE2022-data-generator#8]
Hi, thank you for your excellent work and for sharing it!

I have a question regarding the training data: were all the training samples generated using the real recorded SRIRs available at [this link](https://zenodo.org/records/6408611)? If so, do you find this dataset sufficient for effective model training and for minimizing overfitting risks?

Thank you!

**Comment by danielkrause** [comment]
Hi,

Thank you.

Yes, all training samples were generated using the aforementioned SRIR dataset. The dataset is rather large (and there aren't many other alternatives), so it is a good choice for training models, however if possible, we would advise using even more SRIRs, since from further experiments in recent years it turnt out that the models do not necessarily generalize very well to real data (although the reasons are obviously way more complex than just the SRIRs used in the simulation)

**Comment by ycyang133** [comment]
Thank you very much for your response!

Utilizing this SRIR dataset is a very good choice for training, and I really appreciate your recommendation. If I may ask for a bit more guidance—does the released dataset only include the FOA and MIC formats? I’m very interested in working with the original 32-channel recordings in my research, but I haven't been able to locate them.

Best,
Yichen

**Comment by danielkrause** [comment]
Yes, only the FOA and MIC formats are publicly available. As for now, we don't plan tu publish the 32-channel recordings yet.

**Comment by ycyang133** [comment]
Thank you very much for your response.
Wishing you a wonderful day ahead!
